### ISSUE TITLE
Convert to BusIO

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_VEML6070#10]
https://github.com/adafruit/Adafruit_BusIO

**Comment by caternuson** [comment]
@ladyada I'm thinking of leaving this one as is. It's weird how it has 3 separate **device** (not register) addresses:
```cpp
#define VEML6070_ADDR_H (0x39) ///< High address
#define VEML6070_ADDR_L (0x38) ///< Low address
#define VEML6070_ADDR_ARA                                                      \
  (0x0C) ///< Alert Resp Address (read to clear condition)
```
for such a simple device. There's not a lot going on and making 3 separate instances of an i2cdevice seems unnecessarily clunky.

**Comment by ladyada** [comment]
oh right i remember this weirdo sensor. i think this is maybe the one time it makes sense to *not* use busio

**Comment by caternuson** [comment]
ok. closing. at least this is here for future reference.
